[package]
name = "snake_game"
version = "0.1.0"
authors = ["Ian Pacheco <ianpacheco64@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.49.0"
piston2d-graphics = "0.35.0"
pistoncore-glutin_window = "0.63.0"
piston2d-opengl_graphics = "0.69.0"
rand = "0.4"